FROM ubuntu:20.04

# --- Variables de entorno ---
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/opt/conda/bin:$PATH"

# --- Instalar dependencias básicas ---
RUN apt-get update && apt-get install -y \
    wget curl unzip bzip2 build-essential git \
    python3 python3-pip python3-dev \
    && rm -rf /var/lib/apt/lists/*

# --- Instalar Miniconda ---

RUN curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && rm miniconda.sh && \
    /opt/conda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    /opt/conda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
    /opt/conda/bin/conda update -n base -c defaults conda

# --- Crear entorno con bioinformática 
RUN conda install -y -c conda-forge mamba && \
    mamba install -y -c bioconda -c conda-forge \
        python=3.10 \
        bowtie2=2.5.4 \
        samtools=1.22 && \
    conda clean -afy

# --- Directorio de trabajo
WORKDIR /data

# --- Por defecto: bash ---
CMD ["/bin/bash"]